version: '3.8'

services:
  app:
    image: daydreamer767910/ktt:latest
#    build:
#      context: .
#      dockerfile: Dockerfile
    ports:
      - "7899:7899"
      - "8080:8080"
    env_file:
      - .env
    environment:
      - TZ=America/Los_Angeles
    volumes:
      - E:/ktt/dailybill:/app/dailybill
      - E:/ktt/express:/app/express
      - E:/ktt/logs:/app/logs
    
