name: Publish Docker Image

on:
  push:
    branches:
      - main # 仅在推送到 main 分支时触发

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # Step 1: 检出代码
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: 登录 Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: 构建 Docker 镜像
      - name: Build Docker image
        run: |
          docker build -t daydreamer767910/ktt:latest .

      # Step 4: 推送镜像到 Docker Hub
      - name: Push Docker image
        run: |
          docker push daydreamer767910/ktt:latest
